variable "statement_id" {
  description = "A unique statement identifier. By default generated by Terraform"
}
variable "action" {
  description = "The AWS Lambda action you want to allow in this statement."
}
variable "lambda_function_name" {
  description = "Name of the Lambda function whose resource policy you are updating"
}
variable "principal" {
  description = "The principal who is getting this permission."
}
variable "source_arn" {
  description = "When the principal is an AWS service, the ARN of the specific resource within that service to grant permission to."
}
#variable "qualifier" {
#  description = "Query parameter to specify function version or alias name"
#}